from enum import Enum
class _TYPE_RESISTANCES(Enum):
    SLASHING_RESISTANCE = 0
    BLUDGEONING_RESISTANCE = 1
    FIRE_RESISTANCE = 2
    FROST_RESISTANCE = 3
    POISONOUS_RESISTANCE = 4
    ELECTRIC_RESISTANCE = 5
    MALIGNANT_RESISTANCE = 6
    RADIANT_RESISTANCE = 7
    PSYCHIC_RESISTANCE = 8
    TRUE_RESISTANCE = 9

class _EQUIPMENT_SLOTS(Enum):
    HEAD = 0
    BODY = 1
    HAND = 2
    BOOTS = 3
    ACCESSORY = 4

class _GENDER(Enum):
    MALE = 0
    FEMALE = 1
    HERMAPHRODITE = 2

class _ATTRIBUTE(Enum):
    MUSCLES = 0
    HASTE = 1
    BONES = 2
    BRAIN = 3
    MEMORY = 4
    MAX_HEALTH = 5
    DODGE = 6
    CRITICAL_CHANCE = 7
    CRITICAL_MULTIPLIER = 8
    ACTION_SPEED = 9
    MANA_REGEN = 10
    MAX_MANA = 11
    MELEE_DAMAGE = 12
    RANGED_DAMAGE = 13
    DAMAGE = 14
    VAMPIRISM = 15
    THORNS = 16
    NATURAL_SHIELD = 17
    FAITH = 18
    COUNTERATTACK = 19
    EXTRA_ATTACKS = 20
    HEALTH_REGEN = 21
    
    
class _MODIFIER_TYPE(Enum):
    ADDITIVE = 0
    MULTIPLICATIVE = 1

class _DAMAGE_TYPE(Enum):
    SLASHING = 0
    BLUDGEONING = 1
    FIRE = 2
    FROST = 3
    POISONOUS = 4
    ELECTRIC = 5
    MALIGNANT = 6
    RADIANT = 7
    PSYCHIC = 8
    TRUE_DAMAGE = 9
    
class _ATTACK_DISTANCE(Enum):
    MELEE = 0
    RANGED = 1
    
class _SIDE(Enum):
    PLAYER = 0
    ENEMY = 1

DAMAGE_RESISTANCE_MAP = {
    _DAMAGE_TYPE.SLASHING: _TYPE_RESISTANCES.SLASHING_RESISTANCE,
    _DAMAGE_TYPE.BLUDGEONING: _TYPE_RESISTANCES.BLUDGEONING_RESISTANCE,
    _DAMAGE_TYPE.FIRE: _TYPE_RESISTANCES.FIRE_RESISTANCE,
    _DAMAGE_TYPE.FROST: _TYPE_RESISTANCES.FROST_RESISTANCE,
    _DAMAGE_TYPE.POISONOUS: _TYPE_RESISTANCES.POISONOUS_RESISTANCE,
    _DAMAGE_TYPE.ELECTRIC: _TYPE_RESISTANCES.ELECTRIC_RESISTANCE,
    _DAMAGE_TYPE.MALIGNANT: _TYPE_RESISTANCES.MALIGNANT_RESISTANCE,
    _DAMAGE_TYPE.RADIANT: _TYPE_RESISTANCES.RADIANT_RESISTANCE,
    _DAMAGE_TYPE.PSYCHIC: _TYPE_RESISTANCES.PSYCHIC_RESISTANCE
}

class _GAME_STATE(Enum):
    MENU = 0
    LOBBY = 1
    EXPEDITION = 2
    COMBAT = 3
    LOADING = 4
    TUTORIAL = 5
    
class _DIRECTIONS(Enum):
    UP = 0
    DOWN = 1
    LEFT = 2
    RIGHT = 3

class _SITE(Enum):
    COMBAT = 0
    BAD_EVENT = 1
    NEUTRAL_EVENT = 2
    GOOD_EVENT = 3
    
class _HIERARCHY(Enum):
    COMMONER = 0
    PRINCESS = 1
    QUEEN = 2